#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────
#  VulnHawk — Docker deploy script (Linux)
#
#  Usage:
#    ./deploy.sh                 # interactive first-run setup
#    ./deploy.sh --update        # rebuild image, rolling restart
#    ./deploy.sh --restart       # restart containers (no rebuild)
#    ./deploy.sh --stop          # stop and remove containers
#    ./deploy.sh --logs          # tail live logs
#    ./deploy.sh --status        # show container + health status
#
#  Modes (set LLM_VENDOR in .env):
#    google  — Gemini API key only, no GPU needed
#    ollama  — local Ollama container (requires Docker GPU access)
# ─────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────
RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}▶ $*${RESET}"; }
success() { echo -e "${GREEN}✔ $*${RESET}"; }
warn()    { echo -e "${YELLOW}⚠ $*${RESET}"; }
error()   { echo -e "${RED}✖ $*${RESET}" >&2; }
die()     { error "$*"; exit 1; }
banner()  { echo -e "\n${BOLD}${CYAN}═══ $* ═══${RESET}\n"; }

# ── Paths ────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

ENV_FILE="$SCRIPT_DIR/.env"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"
SERVICE="vulnhawk-api"

# ── Prereqs ──────────────────────────────────────────────────────
check_prereqs() {
    command -v docker >/dev/null 2>&1 || die "Docker is not installed. Install from https://docs.docker.com/engine/install/"
    docker info >/dev/null 2>&1       || die "Docker daemon is not running. Run: sudo systemctl start docker"

    # Prefer 'docker compose' (v2); fall back to 'docker-compose' (v1)
    if docker compose version >/dev/null 2>&1; then
        DC="docker compose"
    elif command -v docker-compose >/dev/null 2>&1; then
        DC="docker-compose"
    else
        die "Docker Compose not found. Install: https://docs.docker.com/compose/install/"
    fi
}

# ── .env setup ───────────────────────────────────────────────────
setup_env() {
    if [[ -f "$ENV_FILE" ]]; then
        info ".env already exists — skipping interactive setup."
        info "Edit $ENV_FILE to change settings, then re-run with --update."
        return
    fi

    banner "First-run Setup"

    echo "Which LLM backend do you want to use?"
    echo "  1) Google Gemini  (recommended — just an API key, no GPU)"
    echo "  2) Ollama         (local container, requires NVIDIA GPU)"
    echo ""
    read -rp "Choice [1/2]: " llm_choice

    case "$llm_choice" in
        2)
            LLM_VENDOR="ollama"
            read -rp "Ollama model [llama3.1]: " OLLAMA_MODEL
            OLLAMA_MODEL="${OLLAMA_MODEL:-llama3.1}"
            read -rp "Ollama base URL [http://ollama:11434]: " OLLAMA_BASE_URL
            OLLAMA_BASE_URL="${OLLAMA_BASE_URL:-http://ollama:11434}"
            GEMINI_API_KEY=""
            ;;
        *)
            LLM_VENDOR="google"
            read -rp "Google Gemini API key: " GEMINI_API_KEY
            [[ -z "$GEMINI_API_KEY" ]] && warn "No API key entered — you can add it to .env later."
            read -rp "Gemini model [gemini-2.0-flash]: " GOOGLE_MODEL
            GOOGLE_MODEL="${GOOGLE_MODEL:-gemini-2.0-flash}"
            OLLAMA_MODEL=""
            OLLAMA_BASE_URL=""
            ;;
    esac

    read -rp "Port to expose VulnHawk on [8000]: " APP_PORT
    APP_PORT="${APP_PORT:-8000}"

    cat > "$ENV_FILE" <<EOF
# VulnHawk environment — generated by deploy.sh

LLM_VENDOR=${LLM_VENDOR}

# Google Gemini
GEMINI_API_KEY=${GEMINI_API_KEY}
GOOGLE_MODEL=${GOOGLE_MODEL:-gemini-2.0-flash}

# Ollama
OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.1}

# Server
APP_PORT=${APP_PORT}
EOF

    chmod 600 "$ENV_FILE"
    success ".env created at $ENV_FILE"
}

# ── Read vendor from .env ─────────────────────────────────────────
get_vendor() {
    grep -E "^LLM_VENDOR=" "$ENV_FILE" 2>/dev/null | cut -d= -f2 | tr -d '[:space:]"'"'" || echo "google"
}

get_port() {
    grep -E "^APP_PORT=" "$ENV_FILE" 2>/dev/null | cut -d= -f2 | tr -d '[:space:]"'"'" || echo "8000"
}

# ── Compose profiles ─────────────────────────────────────────────
compose_args() {
    local vendor
    vendor="$(get_vendor)"
    local args=(-f "$COMPOSE_FILE")
    if [[ "$vendor" == "ollama" ]]; then
        args+=(--profile ollama)
    fi
    echo "${args[*]}"
}

# ── Build ────────────────────────────────────────────────────────
build_image() {
    info "Building Docker image…"
    # shellcheck disable=SC2086
    $DC $(compose_args) build --pull "$SERVICE"
    success "Image built."
}

# ── Ollama model pull ─────────────────────────────────────────────
pull_ollama_model() {
    local vendor model
    vendor="$(get_vendor)"
    [[ "$vendor" != "ollama" ]] && return

    model="$(grep -E "^OLLAMA_MODEL=" "$ENV_FILE" 2>/dev/null | cut -d= -f2 | tr -d '[:space:]"'"'" || echo "llama3.1")"
    info "Pulling Ollama model: $model (this may take a while on first run)…"
    docker exec vulnhawk-ollama-1 ollama pull "$model" 2>/dev/null \
        || $DC $(compose_args) run --rm ollama ollama pull "$model" \
        || warn "Could not pre-pull model — it will download on first use."
}

# ── Start ────────────────────────────────────────────────────────
start_containers() {
    info "Starting containers…"
    # shellcheck disable=SC2086
    $DC $(compose_args) up -d
    success "Containers started."
}

# ── Health wait ───────────────────────────────────────────────────
wait_healthy() {
    local port
    port="$(get_port)"
    info "Waiting for VulnHawk to be healthy on port $port…"

    local attempts=0
    local max=30        # 30 × 5s = 2.5 min
    until curl -sf "http://localhost:${port}/health" >/dev/null 2>&1; do
        attempts=$((attempts + 1))
        if (( attempts >= max )); then
            warn "Health check timed out. Check logs with: ./deploy.sh --logs"
            return 1
        fi
        printf "."
        sleep 5
    done
    echo ""
    success "VulnHawk is up → http://localhost:${port}"
}

# ── Status ───────────────────────────────────────────────────────
show_status() {
    banner "Container Status"
    # shellcheck disable=SC2086
    $DC $(compose_args) ps

    local port
    port="$(get_port)"
    echo ""
    if curl -sf "http://localhost:${port}/health" >/dev/null 2>&1; then
        local health
        health="$(curl -s "http://localhost:${port}/health")"
        success "API healthy — http://localhost:${port}"
        echo "$health" | python3 -m json.tool 2>/dev/null || echo "$health"
    else
        warn "API not responding on port $port"
    fi
}

# ── Commands ─────────────────────────────────────────────────────
cmd_deploy() {
    banner "VulnHawk Deploy"
    check_prereqs
    setup_env
    build_image
    start_containers
    [[ "$(get_vendor)" == "ollama" ]] && pull_ollama_model
    wait_healthy
    echo ""
    success "Deployment complete!"
    echo -e "${BOLD}  UI:     http://localhost:$(get_port)${RESET}"
    echo -e "${BOLD}  Docs:   http://localhost:$(get_port)/docs${RESET}"
    echo -e "${BOLD}  Logs:   ./deploy.sh --logs${RESET}"
}

cmd_update() {
    banner "VulnHawk Update"
    check_prereqs
    [[ ! -f "$ENV_FILE" ]] && die ".env not found. Run ./deploy.sh first."
    build_image
    info "Restarting service with new image…"
    # shellcheck disable=SC2086
    $DC $(compose_args) up -d --no-deps "$SERVICE"
    wait_healthy
    success "Update complete."
}

cmd_restart() {
    banner "VulnHawk Restart"
    check_prereqs
    [[ ! -f "$ENV_FILE" ]] && die ".env not found. Run ./deploy.sh first."
    info "Restarting containers…"
    # shellcheck disable=SC2086
    $DC $(compose_args) restart
    wait_healthy
    success "Restart complete."
}

cmd_stop() {
    banner "VulnHawk Stop"
    check_prereqs
    info "Stopping and removing containers…"
    # shellcheck disable=SC2086
    $DC $(compose_args) down
    success "Containers stopped."
}

cmd_logs() {
    check_prereqs
    # shellcheck disable=SC2086
    $DC $(compose_args) logs -f --tail=100
}

cmd_status() {
    check_prereqs
    [[ ! -f "$ENV_FILE" ]] && die ".env not found. Run ./deploy.sh first."
    show_status
}

# ── Entry point ───────────────────────────────────────────────────
case "${1:-}" in
    --update)  cmd_update  ;;
    --restart) cmd_restart ;;
    --stop)    cmd_stop    ;;
    --logs)    cmd_logs    ;;
    --status)  cmd_status  ;;
    ""|--deploy) cmd_deploy ;;
    *)
        echo "Usage: $0 [--update | --restart | --stop | --logs | --status]"
        exit 1
        ;;
esac
